version: '2'

services:
  # MySQL container
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db

  # App container
  app:
    image: magently/magento2:2.3.1
    links:
      - db
    ports:
      - 80:80
    volumes:
      - ./packages/:/var/www/magento/packages/
      - ./log/:/var/www/magento/var/log/
    environment:
      - PHP_DEBUGGER=none
      - COMPOSER_AUTH={"http-basic":{"repo.magento.com":{"username":"","password":""}}}
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=db
